DROP TABLE cliente CASCADE CONSTRAINT;
DROP TABLE filial CASCADE CONSTRAINT;
DROP TABLE funcionario CASCADE CONSTRAINT;
DROP TABLE dependente CASCADE CONSTRAINT;
DROP TABLE telefoneFuncionario CASCADE CONSTRAINT;
DROP TABLE marca CASCADE CONSTRAINT;
DROP TABLE categoria CASCADE CONSTRAINT;
DROP TABLE caixa CASCADE CONSTRAINT;